dist: trusty
sudo: required
language:
  - generic
cache:
  - apt
services:
  - docker

env:
  - DISTR=indigo  BASEIMG=ros:indigo-robot
  - DISTR=kinetic BASEIMG=ros:kinetic-robot

before_script:
  - docker pull ${BASEIMG}

script:
  - docker build -f Dockerfile.${DISTR} --tag ros:aero_${DISTR} --build-arg RUN_TESTS=true .
